language: python

python: 
  - "3.5"

install: 
  - "pip install pytest-cov"
  - "pip install git+git://github.com/keboola/python-docker-application.git"

script: 
  - "export KBC_DATA_DIR=./test/data"
  - "py.test --cov=keboola --cov-report term-missing"

notifications: 
  slack: "keboola:fym2t4112jahUATYBYFS3oBS"
